services:
  begin_db:
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${BEGIN_USER}
      POSTGRES_PASSWORDWORD: ${BEGIN_PASSWORD}
      POSTGRES_DB: ${BEGIN_DB_NAME}
    volumes:
      - begin_db_data:/var/lib/postgresql/data
    restart: always

volumes:
  begin_db_data: